source 'http://rubygems.org'                                                    
gem 'sinatra'                                                                   
gem 'haml'
gem 'sass'
gem 'redis'
gem 'omniauth-google-oauth2', :git => 'https://github.com/zquestz/omniauth-google-oauth2.git'
